-- MySQL Script generated by MySQL Workbench
-- Tue Jan 14 22:20:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Substance_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Substance_type` (
  `id_Substance_type` INT NOT NULL AUTO_INCREMENT,
  `s_t_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Substance_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Substance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Substance` (
  `id_Substance` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `density` DECIMAL(5,3) UNSIGNED NOT NULL,
  `calorific_value` DECIMAL(5,3) UNSIGNED NOT NULL,
  `min_concentration` TINYINT(3) UNSIGNED NOT NULL,
  `max_concentration` TINYINT(3) UNSIGNED NOT NULL,
  `Substance_type_id_Substance_type` INT NOT NULL,
  PRIMARY KEY (`id_Substance`, `Substance_type_id_Substance_type`),
  INDEX `fk_Substance_Substance_type_idx` (`Substance_type_id_Substance_type` ASC) VISIBLE,
  CONSTRAINT `fk_Substance_Substance_type`
    FOREIGN KEY (`Substance_type_id_Substance_type`)
    REFERENCES `mydb`.`Substance_type` (`id_Substance_type`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
